services:
  n8n:
    image: n8nio/n8n:1.63.0
    container_name: n8n
    restart: no
    env_file: .env
    volumes:
      - n8n_data:/home/node/.n8n
    # ports:
    #   - 5678:5678
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15
    container_name: n8n_postgres
    restart: no
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data_n8n:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d n8ndb -U n8nuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  nginx:
    image: nginx:1.27.0
    restart: no
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - n8n

volumes:
  n8n_data:
  postgres_data_n8n: