# services:
#   prometheus:
#     image: prom/prometheus:v3.3.0
#     container_name: prometheus
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml
#     ports:
#       - "9090:9090"
#     networks:
#       - monitoring

#   grafana:
#     image: grafana/grafana:11.5.5
#     container_name: grafana
#     ports:
#       - "3000:3000"
#     networks:
#       - monitoring
#     volumes:
#       - grafana-storage:/var/lib/grafana

#   node_exporter:
#     image: prom/node-exporter:v1.9.1
#     container_name: node_exporter
#     ports:
#       - "9100:9100"
#     networks:
#       - monitoring

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   networks:
  #     - monitoring

  # blackbox_exporter:
  #   image: prom/blackbox-exporter:v0.26.0
  #   container_name: blackbox_exporter
  #   ports:
  #     - "9115:9115"
  #   volumes:
  #     - ./blackbox.yml:/config/blackbox.yml
  #   command:
  #     - '--config.file=/config/blackbox.yml'
  #   networks:
  #     - monitoring

# networks:
#   monitoring:

# volumes:
#   grafana-storage:

